server:
  port: 8002

spring:
  datasource:
    username: root
    password: lrh,903.520hhhh
    url: jdbc:mysql://sh-cdb-pezvivda.sql.tencentcdb.com:63950/link?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5